python train_mnist.py --experiment_name mnist_v1_exp1 --batch_size 64 --learning_rate 0.00001 --model_params_path ./archs/mnist_blend.json --alpha 1.0
python train_mnist.py --experiment_name mnist_v1_exp2 --batch_size 64 --learning_rate 0.00001 --model_params_path ./archs/mnist_blend.json --alpha 1.0
python train_mnist.py --experiment_name mnist_v1_exp3 --batch_size 64 --learning_rate 0.00001 --model_params_path ./archs/mnist_blend.json --alpha 1.0
python train_mnist.py --experiment_name mnist_v1_exp4 --batch_size 64 --learning_rate 0.00001 --model_params_path ./archs/mnist_blend.json --alpha 1.0
python train_mnist.py --experiment_name mnist_v1_exp5 --batch_size 64 --learning_rate 0.00001 --model_params_path ./archs/mnist_blend.json --alpha 1.0
python train_mnist.py --experiment_name mnist_v1_exp6 --batch_size 64 --learning_rate 0.00001 --model_params_path ./archs/mnist_blend.json --alpha 1.0
python train_mnist.py --experiment_name mnist_v1_exp7 --batch_size 64 --learning_rate 0.00001 --model_params_path ./archs/mnist_blend.json --alpha 0.0
python train_mnist.py --experiment_name mnist_v1_exp8 --batch_size 64 --learning_rate 0.00001 --model_params_path ./archs/mnist_blend.json --alpha 0.0
python train_mnist.py --experiment_name mnist_v1_exp9 --batch_size 64 --learning_rate 0.00001 --model_params_path ./archs/mnist_blend.json --alpha 0.0
python train_mnist.py --experiment_name mnist_v1_exp10 --batch_size 64 --learning_rate 0.00001 --model_params_path ./archs/mnist_blend.json --alpha 0.0
python train_mnist.py --experiment_name mnist_v1_exp11 --batch_size 64 --learning_rate 0.00001 --model_params_path ./archs/mnist_blend.json --alpha 0.0
python train_mnist.py --experiment_name mnist_v1_exp11 --batch_size 64 --learning_rate 0.00001 --model_params_path ./archs/mnist_blend.json --alpha 0.0
