python train.py --experiment_name study_dnn256_cat1 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 0 --model_params_path ./archs/resnet_5_dn6.json
python train.py --experiment_name study_dnn256_cat2 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 0 --model_params_path ./archs/resnet_5_dn6.json
python train.py --experiment_name study_dnn256_cat3 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 0 --model_params_path ./archs/resnet_branch_tanh.json
python train.py --experiment_name study_dnn256_cat4 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 0 --model_params_path ./archs/resnet_branch_tanh.json
python train.py --experiment_name study_dnn256_cat5 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 0 --model_params_path ./archs/resnet_5w2.json
python train.py --experiment_name study_dnn256_cat6 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 0 --model_params_path ./archs/resnet_5w2.json
python train.py --experiment_name study_dnn256_cat7 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 1 --model_params_path ./archs/resnet_5_dn6.json
python train.py --experiment_name study_dnn256_cat8 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 1 --model_params_path ./archs/resnet_5_dn6.json
python train.py --experiment_name study_dnn256_cat9 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 1 --model_params_path ./archs/resnet_branch_tanh.json
python train.py --experiment_name study_dnn256_cat10 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 1 --model_params_path ./archs/resnet_branch_tanh.json
python train.py --experiment_name study_dnn256_cat11 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 1 --model_params_path ./archs/resnet_5w2.json
python train.py --experiment_name study_dnn256_cat12 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 1 --model_params_path ./archs/resnet_5w2.json
python train.py --experiment_name study_dnn256_cat13 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 2 --model_params_path ./archs/resnet_5_dn6.json
python train.py --experiment_name study_dnn256_cat14 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 2 --model_params_path ./archs/resnet_5_dn6.json
python train.py --experiment_name study_dnn256_cat15 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 2 --model_params_path ./archs/resnet_branch_tanh.json
python train.py --experiment_name study_dnn256_cat16 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 2 --model_params_path ./archs/resnet_branch_tanh.json
python train.py --experiment_name study_dnn256_cat17 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 2 --model_params_path ./archs/resnet_5w2.json
python train.py --experiment_name study_dnn256_cat18 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 2 --model_params_path ./archs/resnet_5w2.json
python train.py --experiment_name study_dnn256_cat19 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 3 --model_params_path ./archs/resnet_5_dn6.json
python train.py --experiment_name study_dnn256_cat20 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 3 --model_params_path ./archs/resnet_5_dn6.json
python train.py --experiment_name study_dnn256_cat21 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 3 --model_params_path ./archs/resnet_branch_tanh.json
python train.py --experiment_name study_dnn256_cat22 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 3 --model_params_path ./archs/resnet_branch_tanh.json
python train.py --experiment_name study_dnn256_cat23 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 3 --model_params_path ./archs/resnet_5w2.json
python train.py --experiment_name study_dnn256_cat24 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 3 --model_params_path ./archs/resnet_5w2.json
python train.py --experiment_name study_dnn256_cat25 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 4 --model_params_path ./archs/resnet_5_dn6.json
python train.py --experiment_name study_dnn256_cat26 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 4 --model_params_path ./archs/resnet_5_dn6.json
python train.py --experiment_name study_dnn256_cat27 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 4 --model_params_path ./archs/resnet_branch_tanh.json
python train.py --experiment_name study_dnn256_cat28 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 4 --model_params_path ./archs/resnet_branch_tanh.json
python train.py --experiment_name study_dnn256_cat29 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 4 --model_params_path ./archs/resnet_5w2.json
python train.py --experiment_name study_dnn256_cat30 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 4 --model_params_path ./archs/resnet_5w2.json
python train.py --experiment_name study_dnn256_cat31 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 5 --model_params_path ./archs/resnet_5_dn6.json
python train.py --experiment_name study_dnn256_cat32 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 5 --model_params_path ./archs/resnet_5_dn6.json
python train.py --experiment_name study_dnn256_cat33 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 5 --model_params_path ./archs/resnet_branch_tanh.json
python train.py --experiment_name study_dnn256_cat34 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 5 --model_params_path ./archs/resnet_branch_tanh.json
python train.py --experiment_name study_dnn256_cat35 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 5 --model_params_path ./archs/resnet_5w2.json
python train.py --experiment_name study_dnn256_cat36 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 5 --model_params_path ./archs/resnet_5w2.json
python train.py --experiment_name study_dnn256_cat37 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 6 --model_params_path ./archs/resnet_5_dn6.json
python train.py --experiment_name study_dnn256_cat38 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 6 --model_params_path ./archs/resnet_5_dn6.json
python train.py --experiment_name study_dnn256_cat39 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 6 --model_params_path ./archs/resnet_branch_tanh.json
python train.py --experiment_name study_dnn256_cat40 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 6 --model_params_path ./archs/resnet_branch_tanh.json
python train.py --experiment_name study_dnn256_cat41 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 6 --model_params_path ./archs/resnet_5w2.json
python train.py --experiment_name study_dnn256_cat42 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 6 --model_params_path ./archs/resnet_5w2.json
python train.py --experiment_name study_dnn256_cat43 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 7 --model_params_path ./archs/resnet_5_dn6.json
python train.py --experiment_name study_dnn256_cat44 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 7 --model_params_path ./archs/resnet_5_dn6.json
python train.py --experiment_name study_dnn256_cat45 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 7 --model_params_path ./archs/resnet_branch_tanh.json
python train.py --experiment_name study_dnn256_cat46 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 7 --model_params_path ./archs/resnet_branch_tanh.json
python train.py --experiment_name study_dnn256_cat47 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 7 --model_params_path ./archs/resnet_5w2.json
python train.py --experiment_name study_dnn256_cat48 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 7 --model_params_path ./archs/resnet_5w2.json
python train.py --experiment_name study_dnn256_cat49 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 8 --model_params_path ./archs/resnet_5_dn6.json
python train.py --experiment_name study_dnn256_cat50 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 8 --model_params_path ./archs/resnet_5_dn6.json
python train.py --experiment_name study_dnn256_cat51 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 8 --model_params_path ./archs/resnet_branch_tanh.json
python train.py --experiment_name study_dnn256_cat52 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 8 --model_params_path ./archs/resnet_branch_tanh.json
python train.py --experiment_name study_dnn256_cat53 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 8 --model_params_path ./archs/resnet_5w2.json
python train.py --experiment_name study_dnn256_cat54 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 8 --model_params_path ./archs/resnet_5w2.json
python train.py --experiment_name study_dnn256_cat55 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 9 --model_params_path ./archs/resnet_5_dn6.json
python train.py --experiment_name study_dnn256_cat56 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 9 --model_params_path ./archs/resnet_5_dn6.json
python train.py --experiment_name study_dnn256_cat57 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 9 --model_params_path ./archs/resnet_branch_tanh.json
python train.py --experiment_name study_dnn256_cat58 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 9 --model_params_path ./archs/resnet_branch_tanh.json
python train.py --experiment_name study_dnn256_cat59 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 9 --model_params_path ./archs/resnet_5w2.json
python train.py --experiment_name study_dnn256_cat60 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 9 --model_params_path ./archs/resnet_5w2.json
python train.py --experiment_name study_dnn256_cat61 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 10 --model_params_path ./archs/resnet_5_dn6.json
python train.py --experiment_name study_dnn256_cat62 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 10 --model_params_path ./archs/resnet_5_dn6.json
python train.py --experiment_name study_dnn256_cat63 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 10 --model_params_path ./archs/resnet_branch_tanh.json
python train.py --experiment_name study_dnn256_cat64 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 10 --model_params_path ./archs/resnet_branch_tanh.json
python train.py --experiment_name study_dnn256_cat65 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 10 --model_params_path ./archs/resnet_5w2.json
python train.py --experiment_name study_dnn256_cat66 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 10 --model_params_path ./archs/resnet_5w2.json
python train.py --experiment_name study_dnn256_cat67 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 11 --model_params_path ./archs/resnet_5_dn6.json
python train.py --experiment_name study_dnn256_cat68 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 11 --model_params_path ./archs/resnet_5_dn6.json
python train.py --experiment_name study_dnn256_cat69 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 11 --model_params_path ./archs/resnet_branch_tanh.json
python train.py --experiment_name study_dnn256_cat70 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 11 --model_params_path ./archs/resnet_branch_tanh.json
python train.py --experiment_name study_dnn256_cat71 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 11 --model_params_path ./archs/resnet_5w2.json
python train.py --experiment_name study_dnn256_cat72 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 11 --model_params_path ./archs/resnet_5w2.json
python train.py --experiment_name study_dnn256_cat73 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 12 --model_params_path ./archs/resnet_5_dn6.json
python train.py --experiment_name study_dnn256_cat74 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 12 --model_params_path ./archs/resnet_5_dn6.json
python train.py --experiment_name study_dnn256_cat75 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 12 --model_params_path ./archs/resnet_branch_tanh.json
python train.py --experiment_name study_dnn256_cat76 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 12 --model_params_path ./archs/resnet_branch_tanh.json
python train.py --experiment_name study_dnn256_cat77 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 12 --model_params_path ./archs/resnet_5w2.json
python train.py --experiment_name study_dnn256_cat78 --batch_size 32 --finetune 1 --noise_scale 0.1 --learning_rate 0.00001 --categories 12 --model_params_path ./archs/resnet_5w2.json
