python train.py --experiment_name study_dnn32_stage_v2_1 --batch_size 32 --noise_scale 0.1 --learning_rate 0.00005 --model_params_path ./archs/resnet_branch_relu.json --dropout 0.8
python train.py --experiment_name study_dnn32_stage_v2_2 --batch_size 32 --noise_scale 0.1 --learning_rate 0.00005 --model_params_path ./archs/resnet_branch_elu.json --dropout 0.8
python train.py --experiment_name study_dnn32_stage_v2_3 --batch_size 32 --noise_scale 0.1 --learning_rate 0.00005 --model_params_path ./archs/resnet_branch_tanh.json --dropout 0.8
python train.py --experiment_name study_dnn32_stage_v2_4 --batch_size 32 --noise_scale 0.1 --learning_rate 0.00005 --model_params_path ./archs/resnet_branch_relu2.json --dropout 0.8
python train.py --experiment_name study_dnn32_stage_v2_5 --batch_size 32 --noise_scale 0.1 --learning_rate 0.00005 --model_params_path ./archs/resnet_branch_elu2.json --dropout 0.8
python train.py --experiment_name study_dnn32_stage_v2_6 --batch_size 32 --noise_scale 0.1 --learning_rate 0.00005 --model_params_path ./archs/resnet_branch_tanh2.json --dropout 0.8
python train.py --experiment_name study_dnn32_stage_v2_7 --batch_size 32 --noise_scale 0.1 --learning_rate 0.00005 --model_params_path ./archs/resnet_branch_relu.json --dropout 0.9
python train.py --experiment_name study_dnn32_stage_v2_8 --batch_size 32 --noise_scale 0.1 --learning_rate 0.00005 --model_params_path ./archs/resnet_branch_elu.json --dropout 0.9
python train.py --experiment_name study_dnn32_stage_v2_9 --batch_size 32 --noise_scale 0.1 --learning_rate 0.00005 --model_params_path ./archs/resnet_branch_tanh.json --dropout 0.9
python train.py --experiment_name study_dnn32_stage_v2_10 --batch_size 32 --noise_scale 0.1 --learning_rate 0.00005 --model_params_path ./archs/resnet_branch_relu2.json --dropout 0.9
python train.py --experiment_name study_dnn32_stage_v2_11 --batch_size 32 --noise_scale 0.1 --learning_rate 0.00005 --model_params_path ./archs/resnet_branch_elu2.json --dropout 0.9
python train.py --experiment_name study_dnn32_stage_v2_12 --batch_size 32 --noise_scale 0.1 --learning_rate 0.00005 --model_params_path ./archs/resnet_branch_tanh2.json --dropout 0.9
python train.py --experiment_name study_dnn32_stage_v2_13 --batch_size 32 --noise_scale 0.1 --learning_rate 0.00005 --model_params_path ./archs/resnet_branch_relu.json --dropout 1.0
python train.py --experiment_name study_dnn32_stage_v2_14 --batch_size 32 --noise_scale 0.1 --learning_rate 0.00005 --model_params_path ./archs/resnet_branch_elu.json --dropout 1.0
python train.py --experiment_name study_dnn32_stage_v2_15 --batch_size 32 --noise_scale 0.1 --learning_rate 0.00005 --model_params_path ./archs/resnet_branch_tanh.json --dropout 1.0
python train.py --experiment_name study_dnn32_stage_v2_16 --batch_size 32 --noise_scale 0.1 --learning_rate 0.00005 --model_params_path ./archs/resnet_branch_relu2.json --dropout 1.0
python train.py --experiment_name study_dnn32_stage_v2_17 --batch_size 32 --noise_scale 0.1 --learning_rate 0.00005 --model_params_path ./archs/resnet_branch_elu2.json --dropout 1.0
python train.py --experiment_name study_dnn32_stage_v2_18 --batch_size 32 --noise_scale 0.1 --learning_rate 0.00005 --model_params_path ./archs/resnet_branch_tanh2.json --dropout 1.0
python train.py --experiment_name study_dnn32_stage_v2_19 --batch_size 32 --noise_scale 0.1 --learning_rate 0.00005 --model_params_path ./archs/resnet_branch_relu.json --dropout 0.7
python train.py --experiment_name study_dnn32_stage_v2_20 --batch_size 32 --noise_scale 0.1 --learning_rate 0.00005 --model_params_path ./archs/resnet_branch_elu.json --dropout 0.7
python train.py --experiment_name study_dnn32_stage_v2_21 --batch_size 32 --noise_scale 0.1 --learning_rate 0.00005 --model_params_path ./archs/resnet_branch_tanh.json --dropout 0.7
python train.py --experiment_name study_dnn32_stage_v2_22 --batch_size 32 --noise_scale 0.1 --learning_rate 0.00005 --model_params_path ./archs/resnet_branch_relu2.json --dropout 0.7
python train.py --experiment_name study_dnn32_stage_v2_23 --batch_size 32 --noise_scale 0.1 --learning_rate 0.00005 --model_params_path ./archs/resnet_branch_elu2.json --dropout 0.7
python train.py --experiment_name study_dnn32_stage_v2_24 --batch_size 32 --noise_scale 0.1 --learning_rate 0.00005 --model_params_path ./archs/resnet_branch_tanh2.json --dropout 0.7
